# Generated by Django 4.2 on 2025-05-14 19:35

import coins.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('estimated_value', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10000000)], verbose_name='Оценочная стоимость, ₽')),
                ('image', models.ImageField(upload_to=coins.models.coin_image_path, verbose_name='Фото монеты')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
            ],
            options={
                'verbose_name': 'Монета',
                'verbose_name_plural': 'Монеты',
                'ordering': ['-pub_date'],
            },
        ),
    ]
