# Generated by Django 4.2 on 2025-05-14 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('coins', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('coin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_favorites', to='coins.coin')),
            ],
            options={
                'verbose_name': 'Избранная монета',
                'verbose_name_plural': 'Избранное',
                'ordering': ['-added_at'],
            },
        ),
    ]
