openapi: 3.0.3
info:
  title: Coin Collector API
  description: |
    # API для платформы "Коллекционер монет"
    
    Платформа позволяет нумизматам создавать профили, добавлять монеты в коллекцию,
    описывать их и оценивать, а также взаимодействовать с другими пользователями.
    
    ## Основные возможности
    
    - 🪙 **Управление монетами**: добавление, просмотр, редактирование и удаление монет в коллекции
    - 🏷️ **Теги**: категоризация монет с помощью тегов
    - ⭐ **Избранное**: возможность сохранять интересные монеты в избранное
    - 👥 **Пользователи**: регистрация, авторизация, обновление профиля
    - 🔍 **Поиск и фильтрация**: поиск по названию, фильтрация по стоимости, тегам
    - 📋 **Экспорт**: выгрузка списка избранных монет в Word-документ
    
    ## Аутентификация
    
    API использует JWT-токены для аутентификации. Для доступа к защищенным эндпоинтам необходимо:
    1. Получить токен через /api/auth/jwt/create/
    2. Передавать его в заголовке Authorization: Bearer <token>
    
  version: 1.0.0
  contact:
    name: Разработчик API
    email: developer@coinapi.ru
    url: https://github.com/yourusername/coin-collector
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT

servers:
  - url: http://localhost:8000
    description: Локальный сервер разработки
  - url: https://coin-collector-api.example.com
    description: Тестовый сервер

tags:
  - name: Аутентификация
    description: Эндпоинты для авторизации и работы с токенами
  - name: Пользователи
    description: Управление пользователями и профилями
  - name: Подписки
    description: Подписки на других пользователей
  - name: Монеты
    description: Управление коллекцией монет
  - name: Теги
    description: Управление тегами для категоризации монет
  - name: Избранное
    description: Работа с избранными монетами

paths:
  …  # (все ваши paths, приведённые ранее)

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  parameters:
    PageParam:
      name: page
      in: query
      description: Номер страницы для пагинации
      schema:
        type: integer
        default: 1
        minimum: 1
    PageSizeParam:
      name: page_size
      in: query
      description: Количество элементов на странице
      schema:
        type: integer
        default: 10
        minimum: 1
        maximum: 100

  responses:
    NotFound:
      description: Запрашиваемый объект не найден
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    ValidationError:
      description: Ошибка валидации данных
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ValidationError'
    Unauthorized:
      description: Необходима авторизация
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    Forbidden:
      description: Доступ запрещен
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'

  schemas:
    Error:
      type: object
      properties:
        detail:
          type: string
          example: "У вас нет прав для доступа к этому ресурсу."

    ValidationError:
      type: object
      additionalProperties:
        type: array
        items:
          type: string
      example:
        name:
          - "Обязательное поле."
        email:
          - "Неверный формат email."

    User:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        email:
          type: string
          format: email
        username:
          type: string
          minLength: 3
        first_name:
          type: string
        last_name:
          type: string
        avatar:
          type: string
          format: uri
          nullable: true
          description: URL аватара пользователя
      required:
        - id
        - email
        - username
        - first_name
        - last_name

    UserCreate:
      type: object
      properties:
        email:
          type: string
          format: email
        username:
          type: string
          minLength: 3
        first_name:
          type: string
        last_name:
          type: string
        password:
          type: string
          format: password
          minLength: 8
        avatar:
          type: string
          format: binary
          description: Файл изображения аватара
      required:
        - email
        - username
        - first_name
        - last_name
        - password

    UserUpdate:
      type: object
      properties:
        email:
          type: string
          format: email
        username:
          type: string
          minLength: 3
        first_name:
          type: string
        last_name:
          type: string
        password:
          type: string
          format: password
          minLength: 8
        avatar:
          type: string
          format: binary
          description: Файл изображения аватара

    Subscription:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        subscribed_to:
          type: integer
          description: ID пользователя, на которого оформлена подписка
        created_at:
          type: string
          format: date-time
      required:
        - id
        - subscribed_to

    Coin:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        author:
          $ref: '#/components/schemas/User'
        name:
          type: string
          maxLength: 256
        description:
          type: string
        estimated_value:
          type: integer
          minimum: 1
        tags:
          type: array
          items:
            $ref: '#/components/schemas/Tag'
        image:
          type: string
          format: uri
          description: URL загруженного изображения
        pub_date:
          type: string
          format: date-time
      required:
        - id
        - author
        - name
        - description
        - estimated_value
        - tags
        - image
        - pub_date

    CoinCreate:
      type: object
      properties:
        name:
          type: string
          maxLength: 256
        description:
          type: string
        estimated_value:
          type: integer
          minimum: 1
        tags:
          type: array
          items:
            type: integer
          description: Список ID тегов
        image:
          type: string
          format: binary
          description: Файл изображения монеты
      required:
        - name
        - description
        - estimated_value
        - tags
        - image

    Tag:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        name:
          type: string
          maxLength: 32
        slug:
          type: string
          maxLength: 32
        color:
          type: string
          description: HEX-код цвета для визуального обозначения
      required:
        - id
        - name
        - slug
        - color

    TagCreate:
      type: object
      properties:
        name:
          type: string
          maxLength: 32
        slug:
          type: string
          maxLength: 32
        color:
          type: string
          pattern: '^#([A-Fa-f0-9]{6})$'
      required:
        - name
        - slug
        - color

    Favorite:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        coin:
          $ref: '#/components/schemas/Coin'
        added_at:
          type: string
          format: date-time
      required:
        - id
        - coin

